if(${PROJECT_NAME}_BINDING STREQUAL "")
	message(STATUS "No completion was selected, skipping...")
elseif(NOT ${PROJECT_NAME}_BINDING STREQUAL "")
	foreach(binding ${${PROJECT_NAME}_BINDING})
		if(${binding} STREQUAL python)
			set(PYTHON_SUPPORTED_VERSIONS 2.7 3.5 3.6 3.7 3.8)
			set(PYTHON_VERSION "2.7" CACHE STRING
				"Python version (${PYTHON_SUPPORTED_VERSIONS}) (requires corresponding Boost.Python as well)")
			set(${PROJECT_NAME}_BINDING_PYTHON ON)
		elseif(${binding} STREQUAL ruby)
			set(RUBY_SUPPORTED_VERSIONS 2.1 2.2 2.3 2.4 2.5 2.6)
			set(RUBY_VERSION "2.3" CACHE STRING "Ruby Version (${RUBY_SUPPORTED_VERSIONS})")
			set(${PROJECT_NAME}_BINDING_RUBY ON)
		else()
			message(FATAL_ERROR "Binding '${binding}' stored in variable '${PROJECT_NAME}_BINDING' is not implemented, consider submitting a tracking and/or merge request")
		endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

option(${PROJECT_NAME}_BINDING_PYTHON "FIXME" OFF)
option(${PROJECT_NAME}_BINDING_RUBY "FIXME" OFF)