# FIXME-DOCS(Krey)
if(${PROJECT_NAME}_CLIENT STREQUAL "")
	message(STATUS "No clients were selected, skipping...")
elseif(NOT ${PROJECT_NAME}_CLIENT STREQUAL "")
	foreach(client ${${PROJECT_NAME}_CLIENT})
		if(${client} STREQUAL cave)
			set(${PROJECT_NAME}_CLIENT_CAVE ON)
		else()
			message(FATAL_ERROR "Client '${client}' stored in variable '${PROJECT_NAME}_CLIENT' is not implemented, consider submitting a tracking and/or merge request")
		endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

option(${PROJECT_NAME}_CLIENT_CAVE "FIXME" OFF)