# FIXME-DOCS(Krey)
if(${PROJECT_NAME}_COLOR STREQUAL "")
	message(STATUS "No color-scheme was selected, skipping...")
elseif(NOT ${PROJECT_NAME}_COLOR STREQUAL "")
	foreach(color ${${PROJECT_NAME}_COLOR})
		if(${color} STREQUAL pink)
			set(${PROJECT_NAME}_COLOR ON)
		else()
			message(FATAL_ERROR "Color '${color}' stored in variable '${PROJECT_NAME}_COLOR' is not implemented, consider submitting a tracking and/or merge request")
		endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

option(${PROJECT_NAME}_COLOR_PINK "FIXME" OFF)