# Completions
if(${PROJECT_NAME}_COMPLETION STREQUAL "")
	message(STATUS "No completion was selected, skipping...")
elseif(NOT ${PROJECT_NAME}_COMPLETION STREQUAL "")
	foreach(completion ${${PROJECT_NAME}_COMPLETION})
		if(${completion} STREQUAL bash)
			set(${PROJECT_NAME}_COMPLETION_BASH ON)
		elseif(${completion} STREQUAL zsh)
			set(${PROJECT_NAME}_COMPLETION_ZSH ON)
		else()
			message(FATAL_ERROR "Completion '${completion}' stored in variable '${PROJECT_NAME}_COMPLETION' is not implemented, consider submitting a tracking and/or merge request")
		endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

option(${PROJECT_NAME}_COMPLETION_BASH "FIXME" OFF)
option(${PROJECT_NAME}_COMPLETION_ZSH "FIXME" OFF)
option(${PROJECT_NAME}_COMPLETION_PWSH "FIXME" OFF)
option(${PROJECT_NAME}_COMPLETION_ION "FIXME" OFF)