if(${PROJECT_NAME}_COMPONENT STREQUAL "")
	message(STATUS "No components were selected, skipping...")
elseif(NOT ${PROJECT_NAME}_COMPONENT STREQUAL "")
	foreach(component ${${PROJECT_NAME}_COMPONENT})
	if(${component} STREQUAL xml)
		set(${PROJECT_NAME}_COMPONENT_XML ON)
	elseif(${component} STREQUAL stripper)
		set(${PROJECT_NAME}_COMPONENT_STRIPPER ON)
	elseif(${component} STREQUAL search-index)
		# FIXME-QA(Krey): Add check for sqlite3
		set(${PROJECT_NAME}_COMPONENT_SEARCH_INDEX ON)
	else()
		message(FATAL_ERROR "Completion '${completion}' stored in variable '${PROJECT_NAME}_COMPONENT' is not implemented, consider submitting a tracking and/or merge request")
	endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

option(${PROJECT_NAME}_COMPONENT_XML "FIXME" OFF)
option(${PROJECT_NAME}_COMPONENT_STRIPPER "FIXME" OFF)
option(${PROJECT_NAME}_COMPONENT_SEARCH_INDEX "FIXME" OFF)