# FIXME-QA(Krey): THIS IS UNREADABLE GARBAGE!... There doesn't seem to be a more readable way to do this..
# - Consider MESON x2

# FIXME-DOCS(Krey)
if(${PROJECT_NAME}_DOWNSTEAM STREQUAL "")
	(message STATUS "No color-scheme was selected, skipping...")
elseif(NOT ${PROJECT_NAME}_DOWNSTEAM STREQUAL "")
	foreach(downsteam ${${PROJECT_NAME}_DOWNSTREAM})
		# Mokleus
		if(${downstream} STREQUAL mokleus-0)
			if(${PROJECT_NAME}_COMPONENT_PBIN)
				set(${PROJECT_NAME}_DOWNSTREAM_MOKLEUS_0 ON)
			endif
			set(${PROJECT_NAME}_DOWNSTREAM_MOKLEUS_0 ON)
		elseif(${downstream} STREQUAL pbin-mokleus-0)
			if(${PROJECT_NAME}_COMPONENT_PBIN)
				set(${PROJECT_NAME}_DOWNSTREAM_MOKLEUS_0 ON)
			endif
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_MOKLEUS_0 ON)
		# Exherbo
		elseif(${downstream} STREQUAL exheres-0)
			set(${PROJECT_NAME}_DOWNSTREAM_EXHERES_0 ON)
		elseif(${downstream} STREQUAL pbin-exheres-0)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_EXHERES_0 ON)
		# Gentoo
		# FIXME-QA(Krey): This is unreadable garbage
		elseif(${downstream} STREQUAL gentoo-0)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_0 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-0)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_0 ON)
		elseif(${downstream} STREQUAL gentoo-1)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_1 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-1)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_1 ON)
		elseif(${downstream} STREQUAL gentoo-2)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_2 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-1)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_1 ON)
		elseif(${downstream} STREQUAL gentoo-3)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_3 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-3)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_0 ON)
		elseif(${downstream} STREQUAL gentoo-4)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_4 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-4)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_5 ON)
		elseif(${downstream} STREQUAL gentoo-5)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_5 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-5)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_5 ON)
		elseif(${downstream} STREQUAL gentoo-6)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_6 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-6)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_6 ON)
		elseif(${downstream} STREQUAL gentoo-7)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_7 ON)
		elseif(${downstream} STREQUAL pbin-gentoo-7)
			set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_7 ON)
		# In case 'gentoo' was used to use all gentoo downstream classes
		elseif(${downstream} STREQUAL gentoo)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_0 ON)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_1 ON)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_2 ON)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_3 ON)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_4 ON)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_5 ON)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_6 ON)
			set(${PROJECT_NAME}_DOWNSTREAM_GENTOO_7 ON)
			if(${PALUDIS_NAME}_COMPONENT_PBIN)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_0 ON)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_1 ON)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_2 ON)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_3 ON)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_4 ON)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_5 ON)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_6 ON)
				set(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_7 ON)
			endif
		# Dummy
		elseif(${downstream} STREQUAL PALUDIS-1)
			set(${PROJECT_NAME}_DOWNSTREAM_PALUDIS_1 ON)
		else()
			(message FATAL_ERROR "Dowsntream class '${downstream}' stored in variable '${PROJECT_NAME}_DOWNSTREAM' is not implemented, consider submitting a tracking and/or merge request")
		endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

# Mokleus
option(${PROJECT_NAME}_DOWNSTREAM_MOKLEUS_0 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_MOKLEUS_0 "FIXME" OFF)
# Exherbo
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_EXHERES_0 "FIXME" OFF)
# Gentoo
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_0 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_0 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_1 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_1 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_2 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_2 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_3 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_3 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_4 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_4 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_5 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_5 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_6 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_6 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_GENTOO_7 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_GENTOO_7 "FIXME" OFF)
# Paludis
option(${PROJECT_NAME}_DOWNSTREAM_PALUDIS_1 "FIXME" OFF)
option(${PROJECT_NAME}_DOWNSTREAM_PBIN_PALUDIS_1 "FIXME" OFF)
