if(${PROJECT_NAME}_EDITOR STREQUAL "")
	message(STATUS "No completion was selected, skipping...")
elseif(NOT ${PROJECT_NAME}_EDITOR STREQUAL "")
	foreach(editor ${${PROJECT_NAME}_EDITOR})
		if(${editor} STREQUAL "vim")
			set(${PROJECT_NAME}_EDITOR_VIM ON)
			set(${PROJECT_NAME}_VIM_INSTALL_DIR "${CMAKE_INSTALL_FULL_DATADIR}/vim/vimfiles"
				CACHE PATH "vim installation directory")
		else()
			message(FATAL_ERROR "Editor configuration for editor '${editor}' is not implemented")
		endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

option(${PROJECT_NAME}_EDITOR_VIM "FIXME" OFF)
option(${PROJECT_NAME}_EDITOR_EMACS "FIXME" OFF)
option(${PROJECT_NAME}_EDITOR_NANO "FIXME" OFF)
option(${PROJECT_NAME}_EDITOR_ED "FIXME" OFF)
option(${PROJECT_NAME}_EDITOR_VSCODIUM "FIXME" OFF)
option(${PROJECT_NAME}_EDITOR_VSCODE "FIXME" OFF)
