if(${PROJECT_NAME}_REPOSITORY STREQUAL "")
	(message STATUS "No repositories were specified, skipping...")
elseif(NOT ${PROJECT_NAME}_REPOSITORY STREQUAL "")
	foreach(repository ${${PROJECT_NAME}_REPOSITORY})
		if(${repository} STREQUAL accounts)
			set(${PROJECT_NAME}_REPOSITORY_ACCOUNTS ON)
		elseif(${repository} STREQUAL enoch)
			set(${PROJECT_NAME}_REPOSITORY_ENOCH ON)
		elseif(${repository} STREQUAL fake)
			set(${PROJECT_NAME}_REPOSITORY_FAKE ON)
		elseif(${repository} STREQUAL gemcutter)
			set(${PROJECT_NAME}_REPOSITORY_GEMCUTTER ON)
		elseif(${repository} STREQUAL REPOSITORY)
			set(${PROJECT_NAME}_REPOSITORY_REPOSITORY ON)
		elseif(${repository} STREQUAL unavailable)
			set(${PROJECT_NAME}_REPOSITORY_UNAVAILABLE ON)
		elseif(${repository} STREQUAL unpackaged)
			set(${PROJECT_NAME}_REPOSITORY_UNPACKAGED ON)
		elseif(${repository} STREQUAL unwritten)
			set(${PROJECT_NAME}_REPOSITORY_UNWRITTEN ON)
		else()
			(message FATAL_ERROR "Binding '${binding}' stored in variable '${PROJECT_NAME}_REPOSITORY' is not implemented, consider submitting a tracking and/or merge request")
		endif()
	endforeach()
else()
	message(FATAL_ERROR "UNEXPECTED")
endif()

option(${PROJECT_NAME}_REPOSITORY_PYTHON "FIXME" OFF)
option(${PROJECT_NAME}_REPOSITORY_RUBY "FIXME" OFF)